### ISSUE TITLE
arm-linux-androideabi/bin/ld: warning: cannot scan executable section %d of ./obj/local/armeabi-v7a/%s.a(%s.o) for Cortex-A8 erratum because it has no mapping symbols

### ISSUE THREAD

**Issue by asukakenji** [cocos2d/cocos2d-x#1649]
NDK Version: `r8c`
Cocos2d-x Version: `2.0.4`
Build Command: `ndk-build -B V=1 NDK_DEBUG=0`

When compiling the built-in `samples/TestCpp` application with:

Application.mk:
`APP_ABI := armeabi armeabi-v7a x86`

when building `armeabi-v7a`, the following warnings are shown:

```
StaticLibrary  : libtestcppcommon.a
rm -f obj/local/armeabi-v7a/libtestcppcommon.a
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-ar crs ./obj/local/armeabi-v7a/libtestcppcommon.a ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/AccelerometerTest/AccelerometerTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ActionManagerTest/ActionManagerTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ActionsTest/ActionsTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ActionsEaseTest/ActionsEaseTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ActionsProgressTest/ActionsProgressTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/Box2DTest/Box2dTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/Box2DTestBed/Box2dView.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/Box2DTestBed/GLES-Render.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/Box2DTestBed/Test.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/Box2DTestBed/TestEntries.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-1159.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-1174.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-350.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-422.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-624.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-886.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-899.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-914.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/BugsTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-458/Bug-458.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/BugsTest/Bug-458/QuestionContainerSprite.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ChipmunkAccelTouchTest/ChipmunkAccelTouchTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ClickAndMoveTest/ClickAndMoveTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/CocosDenshionTest/CocosDenshionTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/CurlTest/CurlTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/CurrentLanguageTest/CurrentLanguageTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/DrawPrimitivesTest/DrawPrimitivesTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/EffectsAdvancedTest/EffectsAdvancedTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/EffectsTest/EffectsTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ExtensionsTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/NotificationCenterTest/NotificationCenterTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlScene.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlSceneManager.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlButtonTest/CCControlButtonTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlColourPicker/CCControlColourPickerTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlPotentiometerTest/CCControlPotentiometerTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlSliderTest/CCControlSliderTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlStepperTest/CCControlStepperTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/ControlExtensionTest/CCControlSwitchTest/CCControlSwitchTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/CocosBuilderTest/CocosBuilderTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/CocosBuilderTest/HelloCocosBuilder/HelloCocosBuilderLayer.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/CocosBuilderTest/TestHeader/TestHeaderLayer.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/CocosBuilderTest/ButtonTest/ButtonTestLayer.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/CocosBuilderTest/MenuTest/MenuTestLayer.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/CocosBuilderTest/AnimationsTest/AnimationsTestLayer.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/NetworkTest/HttpClientTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/EditBoxTest/EditBoxTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/TableViewTest/TableViewTestScene.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ExtensionsTest/TableViewTest/CustomTableViewCell.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/FontTest/FontTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/IntervalTest/IntervalTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/KeypadTest/KeypadTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/LabelTest/LabelTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/LayerTest/LayerTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/NodeTest/NodeTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TextInputTest/TextInputTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/MenuTest/MenuTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/MotionStreakTest/MotionStreakTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/MutiTouchTest/MutiTouchTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ParallaxTest/ParallaxTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ParticleTest/ParticleTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/PerformanceTest/PerformanceNodeChildrenTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/PerformanceTest/PerformanceParticleTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/PerformanceTest/PerformanceSpriteTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/PerformanceTest/PerformanceTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/PerformanceTest/PerformanceTextureTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/PerformanceTest/PerformanceTouchesTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/RenderTextureTest/RenderTextureTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/RotateWorldTest/RotateWorldTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/SceneTest/SceneTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/SchedulerTest/SchedulerTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ShaderTest/ShaderTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/SpriteTest/SpriteTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TextureCacheTest/TextureCacheTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/Texture2dTest/Texture2dTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TileMapTest/TileMapTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TouchesTest/Ball.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TouchesTest/Paddle.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TouchesTest/TouchesTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/TransitionsTest/TransitionsTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/UserDefaultTest/UserDefaultTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/ZwoptexTest/ZwoptexTest.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/controller.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/testBasic.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/AppDelegate.o ./obj/local/armeabi-v7a/objs/cocos_testcpp_common/Classes/VisibleRect.o
SharedLibrary  : libtestcpp.so
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-g++ -Wl,-soname,libtestcpp.so -shared --sysroot=/home/asukakenji/android-ndk-r8c/platforms/android-9/arch-arm ./obj/local/armeabi-v7a/objs/testcpp_shared/testcpp/main.o -Wl,--whole-archive ./obj/local/armeabi-v7a/libtestcppcommon.a ./obj/local/armeabi-v7a/libcocos2d.a ./obj/local/armeabi-v7a/libcocosdenshion.a ./obj/local/armeabi-v7a/libbox2d.a ./obj/local/armeabi-v7a/libchipmunk.a ./obj/local/armeabi-v7a/libextension.a ./obj/local/armeabi-v7a/png.a ./obj/local/armeabi-v7a/jpeg.a ./obj/local/armeabi-v7a/xml2.a ./obj/local/armeabi-v7a/tiff.a ./obj/local/armeabi-v7a/curl.a -Wl,--no-whole-archive ./obj/local/armeabi-v7a/libgnustl_static.a  -march=armv7-a -Wl,--fix-cortex-a8  -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -L/home/asukakenji/android-ndk-r8c/platforms/android-9/arch-arm/usr/lib -llog -lz -lGLESv2 -lc -lm -o ./obj/local/armeabi-v7a/libtestcpp.so
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 99 of ./obj/local/armeabi-v7a/png.a(png.o) for Cortex-A8 erratum because it has no mapping symbols.
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 200 of ./obj/local/armeabi-v7a/png.a(pngget.o) for Cortex-A8 erratum because it has no mapping symbols.
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 93 of ./obj/local/armeabi-v7a/png.a(pngpread.o) for Cortex-A8 erratum because it has no mapping symbols.
(... omitted a lot of lines ...)
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 89 of ./obj/local/armeabi-v7a/curl.a(smtp.o) for Cortex-A8 erratum because it has no mapping symbols.
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 13 of ./obj/local/armeabi-v7a/curl.a(rtsp.o) for Cortex-A8 erratum because it has no mapping symbols.
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 4 of ./obj/local/armeabi-v7a/curl.a(http_proxy.o) for Cortex-A8 erratum because it has no mapping symbols.
Install        : libtestcpp.so => libs/armeabi-v7a/libtestcpp.so
install -p ./obj/local/armeabi-v7a/libtestcpp.so ./libs/armeabi-v7a/libtestcpp.so
/home/asukakenji/android-ndk-r8c/toolchains/arm-linux-androideabi-4.6/prebuilt/linux-x86/bin/arm-linux-androideabi-strip --strip-unneeded  ./libs/armeabi-v7a/libtestcpp.so
```

I suspect that the prebuilt binaries (*.a) are not correctly built for `armeabi-v7a`.

**Comment by RonYanDaik** [comment]
Still getting same issue in latest cocos version for libs "tiff", "png", "ttf".

How to avoid?

**Comment by dumganhar** [comment]
Thanks for your feedback. We will check it.

**Comment by minggo** [comment]
Refer to this thread http://code.google.com/p/android/issues/detail?id=40794.

I think the problem is that:
1. r8c makes ld.gold the default linker and this warning doesn't exist in ld.bfd (default linker before r8c).
2. ld.gold needs mapping symbols to fix up for Cortex-A8 hardware erratum(arm-v7a)
3. I have stripped all prebuilt static libs for all architectures

So i think i have to upload unstripped libs for arm-v7a.

**Comment by minggo** [comment]
@RonYanDaik
I have fixed the bug in this PR: https://github.com/cocos2d/cocos2d-x/pull/1891.

**Comment by RonYanDaik** [comment]
Looks like it's ok now. Thx.

**Comment by BeRo1985** [comment]
Could you fix it also for the prebuild spidermonkey android library (for javascript-binding-based projects)? Because it occurs still with the scripting/javascript/spidermonkey-android/lib/libjs_static.a

**Comment by dumganhar** [comment]
> Could you fix it also for the prebuild spidermonkey android library (for javascript-binding-based projects)? Because it occurs still with the scripting/javascript/spidermonkey-android/lib/libjs_static.a

The library of `spiderMonkey` will be very big if not strip it.
If you really need the unstripped library of `SpiderMonkey`, you could go here( https://github.com/ricardoquesada/Spidermonkey ) to build it by your self. Don't forget to comment the `strip` lines in `build.sh`.

**Comment by aberaud** [comment]
I still have this warning with libcurl.a only, with Cocos2dx 2.1.3 and NDK r8e.

**Comment by whitegfx** [comment]
I can confirm the same - warning with libcurl.a only, with Cocos2dx 2.1.3 and NDK r8e.

**Comment by waiter** [comment]
@minggo 
I can confirm the same - warning with libcurl.a only, with Cocos2dx 2.1.3 and NDK r8e.

**Comment by minggo** [comment]
It is strange, i also use NKD r8e.
But i don't have these warnings now.

**Comment by RameshJangama** [comment]
HI Ming, I several time reinstalled everything but still I am able to see NDK r8e, Please can you help;
error: 
C:/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: warning: cannot scan executable section 4 of C:/cocos2d-x/r9/proj.android/../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(ssl_txt.o) for Cortex-A8 erratum because it has no mapping symbols.
C:/android-ndk-r8e/toolchains/arm-linux-androideabi-4.6/prebuilt/windows-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.6/../../../../arm-linux-androideabi/bin/ld.exe: C:/cocos2d-x/r9/proj.android/../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(dso_dlfcn.o): in function dlfcn_pathbyaddr:(.text.dlfcn_pathbyaddr+0xc): error: undefined reference to 'dladdr'
collect2: ld returned 1 exit status
/cygdrive/C/android-ndk-r8e/build/core/build-binary.mk:450: recipe for target `obj/local/armeabi-v7a/libgame.so' failed
make: *** [obj/local/armeabi-v7a/libgame.so] Error 1
make: Leaving directory`/cygdrive/C/cocos2d-x/r9/proj.android'

**Comment by aberaud** [comment]
This is NOT fixed and still happen (at least on linux x86_64) with NDK r9, GCC 4.8, lastest develop branch of cocos2dx.

Easy to reproduce: create a new multi-platform project using the python script, configure for toolchain ndk9 / 4.8 / ARMv7a, and build.

<pre>
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 14 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(file.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 67 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(hostip.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 52 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(formdata.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 49 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(cookie.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 39 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(http.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 124 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(http.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 139 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(http.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 64 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(ftp.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 144 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(ftp.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 174 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(ftp.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 194 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(ftp.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 114 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(url.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 164 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(url.o) for Cortex-A8 erratum because it has no mapping symbols.
android-ndk-r9/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.8/../../../../arm-linux-androideabi/bin/ld: warning: cannot scan executable section 174 of cocos2dx/projects/tdnew/proj.android/../../../cocos2dx/platform/third_party/android/prebuilt/libcurl/libs/armeabi-v7a/libcurl.a(url.o) for Cortex-A8 erratum because it has no mapping symbols.
</pre>

etc.
