### ISSUE TITLE
TextureRendering doesn't work while using GlobalZOrder 

### ISSUE THREAD

**Issue by EladZucker** [cocos2d/cocos2d-x#18614]
- cocos2d-x version: 3.16
- devices test on: windows , IOS, OSX
- developing environments
   - NDK version:
   - Xcode version:
   - VS version: VS2017
   - browser type and version:

Steps to Reproduce:
1.  Write  a simple cocos2dx code in a scene that do the following 
`	Size winSize = Director::getInstance()->getWinSize();

	CCRenderTexture *rt = CCRenderTexture::create(winSize.width, winSize.height);

	rt->begin(); 
	CCDirector::sharedDirector()->getRunningScene()->visit();
	rt->end();
`
In addition make sure to create to sprites and just place on the screen using different globalZOrder. one with globalZorder of 1 and the other with 100.
2. draw the texture on screen you will notice only one or none of the sprites which were on the screen will be displayed.

Bug relates to wrong behavior of the ->visit function while using GlobalZOrder.

**Comment by minggo** [comment]
Could you please give more codes to reproduce it?

**Comment by minggo** [comment]
Oh, i got it. Because render texture uses group command, and it doesn't sorts the commands are added into the group command.

**Comment by minggo** [comment]
Oh, it is not, all commands in render group command also been sorted too, so please add a test case to reproduce it. Thanks.

**Comment by EladZucker** [comment]
What exactly do you need as a test case?

I can easily reproduce it with the self-generate HelloWorld cocos2dx project on 3.16.

Just adding this part of the code to the end of the Init function (or any button callback if you wish) and you will see the issue:
```
	Size winSize = Director::getInstance()->getWinSize();

	CCRenderTexture *rt = CCRenderTexture::create(winSize.width, winSize.height);

	sprite->setGlobalZOrder(1);

	rt->begin();
	CCDirector::sharedDirector()->getRunningScene()->visit();
	rt->end();

	rt->getSprite()->setAnchorPoint(Point(0, 0));
	rt->setPosition(Point(-50, -50));
	
	addChild(rt, 1000);

```

Epected results is that the RenderTexture image will be the same as the one on the screen. added in offest of 50,50 (just to keep the original visual somehow). however, you will see the Cocos HelloWorld image is not visible on the new image.

removing the SetGlobalOrder(1) line of code resolve the issue. which show the texture render missing sprites which are set up in Global Z order. it seems it clipping them right but just doesn't draw them.

In the fourm I posted some pictures so you can see  http://discuss.cocos2d-x.org/t/globalzorder-is-broken-is-so-many-ways/40935/16

**Comment by minggo** [comment]
Thanks, the codes above is what i need. I will try it and give some feedback.

**Comment by minggo** [comment]
fixed in https://github.com/cocos2d/cocos2d-x/pull/18629

**Comment by minggo** [comment]
@EladZucker could you please give some feedback of the PR? Thanks.

**Comment by minggo** [comment]
The PR is reverted because it caused crash issue: https://github.com/cocos2d/cocos2d-x/pull/18777.

**Comment by rh101** [comment]
Any update on a fix for this issue? I noticed the milestone is 3.17.2, but it's not fixed in that release.

**Comment by rh101** [comment]
@minggo The code you originally changed did fix the global Z issue, but as was discovered, it caused a problem in the RenderTextureSave test in RenderTextureTest.cpp.  I just did some testing, and it seems that the reason is because RenderTexture::begin() and RenderTexture::end() are called too many times and too quickly, like what is happening in RenderTextureSave::onTouchesMoved().

It can easily be reproduced with a loop like the following:

```
auto s = Director::getInstance()->getWinSize();

// create a render texture, this is what we are going to draw into
_target = RenderTexture::create(s.width, s.height, Texture2D::PixelFormat::RGBA8888);
_target->retain();
_target->setPosition(Vec2(s.width / 2, s.height / 2));
this->addChild(_target, -1);

for (int i = 0; i < 100; ++i)
{
    // begin drawing to the render texture
    _target->begin();

    Sprite* sprite = Sprite::create("Images/fire.png");
    sprite->setPosition(sprite->getContentSize().width + CCRANDOM_0_1() * (s.width - sprite->getContentSize().width), sprite->getContentSize().height + CCRANDOM_0_1() * (s.height - sprite->getContentSize().height));
    sprite->visit();

    // finish drawing and return context back to the screen
    _target->end();
}
```

I'm not entirely sure why this would cause a problem, since I don't know enough about the rendering system.

Would it perhaps be because _groupCommand, _beginCommand and _endCommand are being overwritten before the commands have been processed (in RenderTexture)? Just taking a wild guess here.

**Comment by rh101** [comment]
@minggo I got it working with your original fix by using a list of group commands, and looping through the list in a circular manner.  The issue is that the RenderTexture::begin() is being called too quickly, re-using the same group.

This is the test code:
```
std::vector<GroupCommand> groupCommands = {
    GroupCommand{},
    GroupCommand{},
    GroupCommand{},
    GroupCommand{},
    GroupCommand{},
    GroupCommand{},
    GroupCommand{},
    GroupCommand{},
};
static int groupIndex = 0;

void RenderTexture::begin()
{
...
...

    auto&& groupCommand = &groupCommands[groupIndex];
    groupIndex = (++groupIndex) % groupCommands.size();
    
    groupCommand->init(_globalZOrder);
    Renderer *renderer =  Director::getInstance()->getRenderer();
    renderer->addCommand(groupCommand);
    renderer->pushGroup(groupCommand->getRenderQueueID());

    _beginCommand.init(INT_MIN);
    _beginCommand.func = CC_CALLBACK_0(RenderTexture::onBegin, this);

    Director::getInstance()->getRenderer()->addCommand(&_beginCommand);
}
```
This code was just for testing out a theory, and while it did fix the issues in #18777 it may not exactly be the optimal fix for the issue.  Is there a way to create/remove a group dynamically?

**Comment by FireMartZ** [comment]
I encountered this issue as well and fixed it by moving the begin/end calls out of the commands group.

![image](https://user-images.githubusercontent.com/24882947/68876337-4b08fb00-06d2-11ea-9d6b-bcc0f6e93d22.png)

This fixed my problem, but I didn't ran the cocos tests suite so I don't know if I broke something else.  Those having the issue may give it a try and I will then submit a PR.
