### ISSUE TITLE
CCEAGLView:setMarkedText problem in iOS13

### ISSUE THREAD

**Issue by lxhhuangjin** [cocos2d/cocos2d-x#20174]
- cocos2d-x version: 3.12
- devices test on: iPhone
- developing environments
   - NDK version:
   - Xcode version:
   - VS version:
   - browser type and version:

Steps to Reproduce:
input Chinese in TextField just recieve one charactor in setMarketedText , input number or English both ok.

**Comment by lxhhuangjin** [comment]
be the same question with https://github.com/cocos2d/cocos2d-x/issues/20050

**Comment by wandeli** [comment]
- (NSString *)textInRange:(UITextRange *)range
{
    CCLOG("textInRange");
    if (nil != markedText_) {
        return markedText_;
    }
    return @"";
}

- (UITextRange *)markedTextRange
{
    CCLOG("markedTextRange");
    if (nil != markedText_) {
        return [[[UITextRange alloc] init] autorelease];
    }
    return nil; // Nil if no marked text.
}

**Comment by lxhhuangjin** [comment]
> 
> 
>     * (NSString *)textInRange:(UITextRange *)range
>       {
>       CCLOG("textInRange");
>       if (nil != markedText_) {
>       return markedText_;
>       }
>       return @"";
>       }
> 
>     * (UITextRange *)markedTextRange
>       {
>       CCLOG("markedTextRange");
>       if (nil != markedText_) {
>       return [[[UITextRange alloc] init] autorelease];
>       }
>       return nil; // Nil if no marked text.
>       }

I have tried this code. The input of Chinese is ok. But when i click the screen to close IME. The IME open again. I debug this performance and find i recieved UIKeyboardWillShowNotification.

**Comment by minggo** [comment]
I don't know what's the problem, i can input Chinese characters with iPhone11(iOS 13).

**Comment by lxhhuangjin** [comment]
My iPhone X(iOS13) input Chinese in
 TextField has problem. The function named setMarkedText just received one charactor I input recently.

**Comment by minggo** [comment]
What test case did you test?

**Comment by lxhhuangjin** [comment]
> 
> 
> What test case did you test?

Any input is ok. 
eg. First i input 'w', setMarkedText  recieved 'w', then input 'd', setMarkedText  recieved 'd'. But setMarkedText  need recieve 'wd'.

**Comment by minggo** [comment]
Did you use TextFieldTTF? Please show your test case and the steps to reproduce it. Thanks.

**Comment by lxhhuangjin** [comment]
Yes. I use TextFieldTTF for input.
I want to input Chinese like "我的" on iPhone. 
So i input 'wd' for the words. But the input result is not correct. The result did not change compared with the input when i open IME. 
I debuged for this problem. I fond the problem is the function or setMarkedText.
I think you can reproduce this problem by any iPhone when update to iOS 13. I tried iPhoneXR and iPhoneXS Max.

**Comment by minggo** [comment]
As i said above, i tested `TextInput` and change to use `Arial`, then can input Chinese. You should check your ttf file support Chinese characters.

**Comment by lxhhuangjin** [comment]
> 
> 
> As i said above, i tested `TextInput` and change to use `Arial`, then can input Chinese. You should check your ttf file support Chinese characters.

I can input Chinese properly before i update my iPhone to iOS 13.

**Comment by minggo** [comment]
I tested on iPhone11 with iOS13.

**Comment by minggo** [comment]
I tried iPhone8 with iOS 13, can reproduce it.

**Comment by lxhhuangjin** [comment]
> 
> 
> I tested on iPhone11 with iOS13.

I tried the code of @wandeli and the problem has been resolved. But  when i close the IME and touch screen where do not have textfield, the IME opened. This is another problem. But i think his code is a correct direction for this problem.

**Comment by minggo** [comment]
It is because engine can not receive `touches end` event, but i don't know why. If don't modify `markedTextRange `, then can just input a character a time.

**Comment by lxhhuangjin** [comment]
> 
> 
> It is because engine can not receive `touches end` event, but i don't know why. If don't modify `markedTextRange `, then can just input a character a time.

Maybe i should modify _setMarkedText_ and concat string by myself in iOS13.

**Comment by wandeli** [comment]
- (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent *)event
{
    for (UIGestureRecognizer* ges in [self gestureRecognizers])
    {
        [self removeGestureRecognizer:ges];
    }

add this can receive touches end even

**Comment by Kafka2** [comment]
> * (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent _)event
>   {
>   for (UIGestureRecognizer_ ges in [self gestureRecognizers])
>   {
>   [self removeGestureRecognizer:ges];
>   }
> 
> add this can receive touches end even

Still have problems

**Comment by Kafka2** [comment]
> * (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent _)event
>   {
>   for (UIGestureRecognizer_ ges in [self gestureRecognizers])
>   {
>   [self removeGestureRecognizer:ges];
>   }
> 
> add this can receive touches end even

and also add this in touches cancel event.


But I don't know why UIKit adds a sort of GestureRecognizers in iOS 13+

**Comment by minggo** [comment]
@wandeli it may slow down the performance of touch events. And it is strange that iPhone11 with iOS 13 doesn't have problem.

**Comment by Kafka2** [comment]
> @wandeli it may slow down the performance of touch events. And it is strange that iPhone11 with iOS 13 doesn't have problem.

I reproduced the problem in iPhone11 with iOS 13.1.2 using system input method.

**Comment by minggo** [comment]
My iPhone 11 is updated to iOS 13.1.2, and there is not problem. I don't use system input method, use `搜狗`.

**Comment by minggo** [comment]
I uses `搜狗` instead of system input method, it works on iPhone 8(13.0) too. So the problem exists in system input method.

**Comment by lxhhuangjin** [comment]
> 
> 
> > * (void)touchesBegan:(NSSet *)touches withEvent:(UIEvent _)event
> >   {
> >   for (UIGestureRecognizer_ ges in [self gestureRecognizers])
> >   {
> >   [self removeGestureRecognizer:ges];
> >   }
> > 
> > add this can receive touches end even
> 
> and also add this in touches cancel event.
> 
> But I don't know why UIKit adds a sort of GestureRecognizers in iOS 13+

Maybe related to QuickPath in iOS 13+. This is the new function in iOS 13+ and seems like related to GestureRecognizers.

**Comment by huachangmiao** [comment]
@minggo 
Is there any progress?

**Comment by pandaGames** [comment]
same issue.use system input method can reproduce the problem.but **editbox** works fine in iOS13.

**Comment by minggo** [comment]
@huachangmiao sorry, there is not progress. I will continue to fix it.
@pandaGames `EditBox` uses UIKit component.

**Comment by wordes** [comment]
@minggo
Is there any progress?

**Comment by huangwei1024** [comment]
we also encounter the same problem, in cocos2dx 3.X and ios 13.1

**Comment by EricDDK** [comment]
I change 2 functions and everything is OK.
```
static UITextRange * s_textRange = [[UITextRange alloc] init];

- (UITextRange *)markedTextRange;
{
    CCLOG("markedTextRange");
    if (nil != markedText_) {
        return s_textRange;
    }
    return nil; // Nil if no marked text.
}
```
```
- (NSString *)textInRange:(UITextRange *)range;
{
    CCLOG("textInRange");
    if (nil != markedText_) {
        return markedText_;
    }
    return @"";
}
```

**Comment by Kafka2** [comment]
@EricDDK it triggers the same issue related to GestureRecognizors.

**Comment by EricDDK** [comment]
> @EricDDK it triggers the same issue related to GestureRecognizors.

What's the problem?

**Comment by EricDDK** [comment]
> @EricDDK it triggers the same issue related to GestureRecognizors.

I dont know what happens. I test it on my app within cocos2d-x 3.7.1 and Xcode11.1. iphone is iOS 13.2
Everything is Okay, the memory is normal, and the performance is well.

**Comment by Kafka2** [comment]
> > ```
> > * (NSString *)textInRange:(UITextRange *)range
> >   {
> >   CCLOG("textInRange");
> >   if (nil != markedText_) {
> >   return markedText_;
> >   }
> >   return @"";
> >   }
> > 
> > * (UITextRange *)markedTextRange
> >   {
> >   CCLOG("markedTextRange");
> >   if (nil != markedText_) {
> >   return [[[UITextRange alloc] init] autorelease];
> >   }
> >   return nil; // Nil if no marked text.
> >   }
> > ```
> 
> 
> I have tried this code. The input of Chinese is ok. But when i click the screen to close IME. The IME open again. I debug this performance and find i recieved UIKeyboardWillShowNotification.

@EricDDK

**Comment by EricDDK** [comment]
> > > ```
> > > * (NSString *)textInRange:(UITextRange *)range
> > >   {
> > >   CCLOG("textInRange");
> > >   if (nil != markedText_) {
> > >   return markedText_;
> > >   }
> > >   return @"";
> > >   }
> > > 
> > > * (UITextRange *)markedTextRange
> > >   {
> > >   CCLOG("markedTextRange");
> > >   if (nil != markedText_) {
> > >   return [[[UITextRange alloc] init] autorelease];
> > >   }
> > >   return nil; // Nil if no marked text.
> > >   }
> > > ```
> > 
> > 
> > I have tried this code. The input of Chinese is ok. But when i click the screen to close IME. The IME open again. I debug this performance and find i recieved UIKeyboardWillShowNotification.
> 
> @EricDDK

But my app is Okay.  click the screen to close IME. The IME open again? I can close the IME.

**Comment by wordes** [comment]
@EricDDK There was a problem after input of Chinese.

**Comment by minggo** [comment]
I sent https://github.com/cocos2d/cocos2d-x/pull/20209 to fix it. 

The application should handle touch cancel event to close keyboard.

**Comment by minggo** [comment]
Any feedback is appreciated.

**Comment by minggo** [comment]
Does anybody test it?

**Comment by Kafka2** [comment]
@minggo still have the same problem related to GestureRecognizors.

**Comment by 1xiaoming1314** [comment]
@minggo I test in ios 13 by your way, that will crash.

**Comment by minggo** [comment]
What test case did you test? I tested `TextInput` of cpp-tests on iOS 13, it works.

**Comment by 1xiaoming1314** [comment]
i test in my games by cocos2d-2.0-x-2.04
crash log：[EAGLView selectionRectsForRange:]: unrecognized selector sent to instance 0x7f8c4e70c440

**Comment by minggo** [comment]
v2 is very different from v3, i think you should modify it according the PR yourself.

**Comment by re-esper** [comment]
> Does anybody test it?

I tested it on cocos2d-x lua 3.14 yesterday, it works very well.
But it means no more touchcancel events? So finally, I used removeGestureRecognizer method above instead.

**Comment by minggo** [comment]
> But it means no more touchcancel events? 

What did you mean?

**Comment by re-esper** [comment]
> > But it means no more touchcancel events?
> 
> What did you mean?

the commit code shows that touchcancel events redirect to touchend. For lua, I made it in objective-c touchesCancelled callback, so no touchcancel events anymore for lua.

**Comment by minggo** [comment]
@re-esper i did it in the test case just for convenient. In your codes, you can handle touch cancel event in its own function.

**Comment by re-esper** [comment]
@minggo but even so, after user input some chinese words and close IME, any touch ends with touchcancel instead of  touchend, so we dont know which is real touchcancel after that?

**Comment by minggo** [comment]
Sorry, i don't quite understand. Could you please describe it in more detail?

**Comment by minggo** [comment]
You can use Chinese and paste its translation if you have trouble in describing it in English.

**Comment by re-esper** [comment]
@minggo 我通过log发现, 输入汉字然后点空白区域关闭输入法后, 游戏中所有触摸操作已经不再能收到touchend而是收到touchcancel结束, 这样是否意味着已经不能直接区分哪些touchcancel是真正的touchcancel了?


I found through the log that after inputting the Chinese characters and then clicking the blank area to close the input method, all the touch operations in the game can no longer receive the touchend but receive the touchcancel end. Does this mean that it is no longer possible to directly distinguish which touchcancel is the real touchcancel? ?

**Comment by minggo** [comment]
I have tested `TextInput`, after closing keyboard, application can receive touch end events. I don't know why you can't. It is better if you can provide a demo to reproduce it.

**Comment by yanggee** [comment]
I have tested `TextInput`, after closing keyboard by keyboard's `send`, application can't recevie touch end events. but, when I click  screnn without keyboard to close it,, it's ok. application can receive touch end events.
the device is iphone x, iOS 13.1.2.
@Miigon 在iphonx上面，我点击空白区域关闭输入法，游戏中触摸操作是正常的，但是点击键盘上面的换行，关闭键盘后，游戏就不能相应touchend方法了

**Comment by minggo** [comment]
@re-esper sorry, you are right. I didn't use system input method in my test. If using system input method, then can not receive touch end method.

**Comment by yanggee** [comment]
so, what should i do for fix it ?

**Comment by yanggee** [comment]
> @re-esper sorry, you are right. I didn't use system input method in my test. If using system input method, then can not receive touch end method.

so,  What should i do to fix it ?

**Comment by minggo** [comment]
I have not idea right now.

**Comment by minggo** [comment]
I updated the pull request, i think it works now.

**Comment by yanggee** [comment]
> I updated the pull request, i think it works now.

thank you! it's ok.

**Comment by minggo** [comment]
@yanggee thanks for your feedback.
@re-esper @Kafka2 @wordes @lxhhuangjin any feedback?

**Comment by Guy-kun** [comment]
Just a comment to confirm that this issue exists for the flick keyboard input in Japanese on iOS13, I currently don't have time but will try testing the PR soon.

**Comment by Guy-kun** [comment]
I had some time to test this as it's happening for Japanese input on iOS13 too and am seeing the following:

fixed in MR:
- typing in and pressing enter to close japanese qwerty keyboard

not fixed in MR:
- tapping outside keyboard to close either keyboard (app stops receiving touches)
- typing with japanese kana keyboard (flick 10key)  in ABC english mode (input does not get passed to app)

**Comment by minggo** [comment]
@Guy-kun what did you mean `MR`? Does it mean the `PR`(short for pull request)? I don't know Japanese input, but i think it is the same as Chinese input.

**Comment by Guy-kun** [comment]
Yes, I mean the PR sorry about that.
I tested Japanese input with the PR and it is not working, as stated above.

**Comment by minggo** [comment]
@Guy-kun sorry, i have not idea. I think you should modify it according the PR.

**Comment by minggo** [comment]
@Guy-kun yep, it can not work, i think i made some mistake in refactoring codes. I sent https://github.com/cocos2d/cocos2d-x/pull/20232 to fix it based on #20209.

**Comment by Guy-kun** [comment]
Appears to be working from some quick tests!
We'll QA properly and report if there's any further issues

**Comment by Guy-kun** [comment]
This appears to still have an issue with:
`tapping outside keyboard to close either keyboard (app stops receiving touches)`
as previously.

It seems to be fairly inconsistent and repeatedly tapping outside of the keyboard to close it (2 or 3 times) will make touches stop responding correctly in-app. The view may possibly be getting offset/moved incorrectly as this seems inconsistent?

This happens even with the standard english keyboard after the PR.

**Comment by Guy-kun** [comment]
@minggo any chance of taking a look at this again?

**Comment by minggo** [comment]
How to reproduce it? Could you please describe it in more detail?

**Comment by minggo** [comment]
I tested `text-input` in cpp-tests:
- click screen to pop up keyboard
- click outside of keyboard to close it
- repeat above operations many times

App can response touch events correctly. If you don't mind, would you please use v3 latest codes to test?

**Comment by huangwei1024** [comment]
I merged #20232 #20209 #20250 in my proj.

you need add a background layer. it will hide widget when you touch the background. 
like this

```
		local blackLayer = ccui.Layout:create()
		blackLayer:setContentSize(display.sizeInView)
		blackLayer:setBackGroundColorType(1)
		blackLayer:setBackGroundColor(color)
		blackLayer:setOpacity(0)
		blackLayer:setTouchEnabled(true)
		blackLayer:setPosition(cc.p(display.board_left, 0))
		bind.click(self, blackLayer, {method = function()
			self:onClose()
		end})
```

#20281 was use background layer. 

if you not had other layers, the problem was some touch had no effect.

**Comment by minggo** [comment]
@huangwei1024 please provide a demo to reproduce it.

**Comment by lxhhuangjin** [comment]
@minggo I had tried the new code on iOS 10.3 and find a problem.When i input charactor for Chinese, no predict text appear. In addition to Chinese, i input number or English is ok. So i compare these code with the last version and find these code has been deleted.I want know why. And i add these code, the input for Chinese can be work.
`- (UITextRange *)selectedTextRange;
{
    return [[[UITextRange alloc] init] autorelease];
}`

**Comment by minggo** [comment]
@lxhhuangjin as it works without it when i tested, and selected text means the text selected in a view. So i deleted it to make codes clean. The usage of `UITextInput` is wired in engine, indeed i don't quite understand all the protocol.

**Comment by lxhhuangjin** [comment]
@minggo You can reproduce the problem i described on iOS10.

**Comment by lxhhuangjin** [comment]
@minggo Another problem. When i open keyboard by EditBox, the keyboard can not  be closed when i click the screen out of the keyboard. The function named "onUIKeyboardNotication" need belong with CCEAGLView in my opinion.

**Comment by minggo** [comment]
> @minggo Another problem. When i open keyboard by EditBox, the keyboard can not be closed when i click the screen out of the keyboard. The function named "onUIKeyboardNotication" need belong with CCEAGLView in my opinion.

I think it is fixed in https://github.com/cocos2d/cocos2d-x/pull/20250.

**Comment by lxhhuangjin** [comment]
@minggo You can see the code in CCUIEditBoxIOS.mm.
`- (void)openKeyboard
{
    auto view = cocos2d::Director::getInstance()->getOpenGLView();
    CCEAGLView *eaglview = (CCEAGLView *)view->getEAGLView();
    [eaglview addSubview:self.textInput];
    [self.textInput becomeFirstResponder];
}`
The InputView was add to EAGLView. But EAGLView do not listen to the event of didMoveToWindow.

**Comment by Guy-kun** [comment]
I'm having problems setting up a latest test project due to my current cocos environment/version and can't finish it today but I'm aiming to try the following code where I presume touches to the button will stop working/be in an incorrect position?

```
    auto textField = ui::TextField::create();
    textField->setPosition(Vec2(this->getContentSize().width/2 , this->getContentSize().height/2 - 50));
    this->addChild(textField);
    
    auto testButton = ui::Button::create("HelloWorld.png");
    testButton->setTitleText("Tap");
    
    this->addChild(testButton);

    testButton->setPosition(this->getContentSize()/2);
              
    testButton->addTouchEventListener([&,testButton](Ref* pSender, cocos2d::ui::Widget::TouchEventType type) {
        if (type == cocos2d::ui::Widget::TouchEventType::ENDED)
        {
            testButton->setOpacity(0);
            testButton->runAction(FadeTo::create(1, 255));
            
        }
    });
```

**Comment by minggo** [comment]
> The InputView was add to EAGLView. But EAGLView do not listen to the event of didMoveToWindow.

@lxhhuangjin `CCInputView` do it. And i will add `selectedTextRange` back.

**Comment by minggo** [comment]
@lxhhuangjin ok, i got your idea, you mean the function should be added in `CCEAGLView`, yep, i think you are right.

**Comment by lxhhuangjin** [comment]
@minggo I am glad to see you know what i mean. Ok, waiting for your update of the code.

**Comment by minggo** [comment]
I sent https://github.com/cocos2d/cocos2d-x/pull/20294, hope it fixes all issues. I tested on iPhone11(iOS 13.1.2), iPhone8(iOS 13.1.3) and iPhone5s(iOS 12.4).

**Comment by Guy-kun** [comment]
It's extremely hard to see if this is fixed as we use an older version of v3 to which I can't apply patches directly due to differences...
Is there any reason for sending 4 PRs for this fix rather than updating a single one?? it makes it so much harder to manage manually merging them in...

To reiterate, this issue now is affected by 4 PRs
 #20232 #20209 #20250 #20294

**Comment by Guy-kun** [comment]
I've reproduced the cause of the issue I'm having @minggo 
This also happens on latest v3 in a test project using the simple textview code I sent previously.

It appears that when tapping to dismiss the keyboard outside of it's bounds `CCEAGLView::touchesBegan` is called, but there are no subsequent calls `touchesEnded` or `touchesCancelled`

This results in `CCGLView` not decrementing `unusedIndex` and therefore tracking all subsequent touches as +1 in touchID. This seems like a real issue that needs fixing as it breaks touch IDs
(Our UI was customized to reject touches >1 in order to prevent accidental multitouch misfires resulting in it 'not working' anymore) Repeats of these steps will repeatedly increment the current touchID of new touches

I can't find any cause for `touchesEnded` not being called so I'll have to leave it as a report here unfortunately that needs fixing.

**Comment by minggo** [comment]
@Guy-kun sorry about so many PRs, it is because i thought it is fixed as i tested myself. Maybe the test case i used is not good enough to reproduce the issue. And i don't think you need to apply PR one by one, it only affects CCEAGLview and adding CCInputVie, you can just replace these two files to test.

About the touch end missing issue i will take a look, but i am not sure if i can fix it if it has the issue. Maybe you can create a new issue as the issue is not the same as this one.

**Comment by minggo** [comment]
@Guy-kun i sent https://github.com/cocos2d/cocos2d-x/pull/20303 to fix it. This time i will not merge the PR until some of you confirm that the issue is resolved.

**Comment by Guy-kun** [comment]
Thanks very much, I've left a comment that we'll test it more but it seems to be good at a quick check.

As for why the 4x merges were hard, as stated before we are using an earlier v3 of cocos and can't apply a patch on top of CCEAGLView due to possibly incompatibility as it does not match this 3.17 codebase...
It seems to be resolved though for now!
